builds:
  - main: ./cmd/cert/main.go
    binary: cert
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - 386
archive:
  name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
  files:
    - README.md
  format_overrides:
    - goos: windows
      format: zip
release:
  github:
    owner: genkiroid
    name: cert
